import { OpenSearchResource } from './open-search.service';

export const mockOpenSearchResources: OpenSearchResource[] = [
  {
    id: 'component:root:orgs:sap:workspaces:dxp-system:organization-ui',
    score: 12.34,
    resource: 'components',
    kind: 'Component',
    name: 'organization-ui',
    namespace: 'dxp-system',
    apiGroup: 'metadata.dxp.sap.com',
    apiVersion: 'v1alpha1',
    workspacePath: 'root:orgs:sap:workspaces',
    clusterName: 'sap-workspaces',
    organizationId: 'sap',
    organizationName: 'SAP',
    accountId: 'workspaces',
    accountName: 'Workspaces',
    source: {
      id: 'component:root:orgs:sap:workspaces:dxp-system:organization-ui',
      kind: 'Component',
      name: 'organization-ui',
      namespace: 'dxp-system',
      api_group: 'metadata.dxp.sap.com',
      api_version: 'v1alpha1',
      workspace_path: 'root:orgs:sap:workspaces',
      cluster_name: 'sap-workspaces',
      organization_id: 'sap',
      organization_name: 'SAP',
      account_id: 'workspaces',
      account_name: 'Workspaces',
      default_fields: {
        'metadata.name': 'a0',
        'spec.URL': 'https://localhost:8443/clusters/root:orgs:sub:a0',
        'spec.type.name': 'sub-account',
        'spec.type.path': 'root:orgs',
      },
      filterable_fields: {
        'metadata.namespace': 'dxp-system',
        'metadata.name': 'a0',
      },
      semantic_fields: {
        'spec.description': 'Frontend for managing Hyperspace Portal organizations',
      },
    },
  },
  {
    id: 'api:root:orgs:sap:dev:platform-system:gateway-api',
    score: 9.87,
    resource: 'apis',
    kind: 'API',
    name: 'gateway-api',
    namespace: 'platform-system',
    apiGroup: 'metadata.dxp.sap.com',
    apiVersion: 'v1alpha1',
    workspacePath: 'root:orgs:sap:dev',
    clusterName: 'sap-dev',
    organizationId: 'sap',
    organizationName: 'SAP',
    accountId: 'dev',
    accountName: 'Development',
    source: {
      id: 'api:root:orgs:sap:dev:platform-system:gateway-api',
      kind: 'API',
      name: 'gateway-api',
      namespace: 'platform-system',
      api_group: 'metadata.dxp.sap.com',
      api_version: 'v1alpha1',
      workspace_path: 'root:orgs:sap:dev',
      cluster_name: 'sap-dev',
      organization_id: 'sap',
      organization_name: 'SAP',
      account_id: 'dev',
      account_name: 'Development',
      default_fields: {
        'metadata.name': 'gateway-api',
        'spec.URL': 'https://localhost:8443/clusters/root:orgs:sap:dev',
        'spec.type.name': 'openapi',
        'spec.type.path': 'root:orgs:sap',
      },
      filterable_fields: {
        'metadata.namespace': 'platform-system',
        'metadata.name': 'gateway-api',
      },
      semantic_fields: {
        'spec.description': 'REST gateway API for the Platform Mesh control plane',
      },
    },
  },
  {
    id: 'service:root:orgs:sap:staging:mesh-system:auth-service',
    score: 7.52,
    resource: 'services',
    kind: 'Service',
    name: 'auth-service',
    namespace: 'mesh-system',
    apiGroup: 'metadata.dxp.sap.com',
    apiVersion: 'v1alpha1',
    workspacePath: 'root:orgs:sap:staging',
    clusterName: 'sap-staging',
    organizationId: 'sap',
    organizationName: 'SAP',
    accountId: 'staging',
    accountName: 'Staging',
    source: {
      id: 'service:root:orgs:sap:staging:mesh-system:auth-service',
      kind: 'Service',
      name: 'auth-service',
      namespace: 'mesh-system',
      api_group: 'metadata.dxp.sap.com',
      api_version: 'v1alpha1',
      workspace_path: 'root:orgs:sap:staging',
      cluster_name: 'sap-staging',
      organization_id: 'sap',
      organization_name: 'SAP',
      account_id: 'staging',
      account_name: 'Staging',
      default_fields: {
        'metadata.name': 'auth-service',
        'spec.URL': 'https://localhost:8443/clusters/root:orgs:sap:staging',
        'spec.type.name': 'oidc-provider',
        'spec.type.path': 'root:orgs:sap',
      },
      filterable_fields: {
        'metadata.namespace': 'mesh-system',
        'metadata.name': 'auth-service',
      },
      semantic_fields: {
        'spec.description': 'OIDC authentication service for the Platform Mesh ecosystem',
      },
    },
  },
];
