name: auto-labeler

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  auto-labeler:
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: platform-mesh/.github/.github/workflows/job-auto-labeler.yml@33d3ee309a70b300c1775d78054cbb9215673b7b
    permissions:
      contents: read # Needed for actions/checkout in the reusable
      pull-requests: write # Needed to add labels to pull requests
      issues: write # Needed to manage labels used by the labeler
