name: OpenSSF Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '30 4 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    uses: platform-mesh/.github/.github/workflows/job-ossf-scorecard.yml@33d3ee309a70b300c1775d78054cbb9215673b7b
    permissions:
      security-events: write # Needed to upload the Scorecard SARIF to code scanning
      id-token: write # Needed for the OIDC token when publishing Scorecard results
      contents: read # Needed to read repository contents during analysis
      actions: read # Needed by Scorecard to read workflow run metadata
